- name: Install Python 3.8
  apt:
    name: python3.8
    state: present
    update_cache: yes

- name: Install pip3
  apt:
    name: 
    - python3-pip
    - python-setuptools
    state: present
    update_cache: yes

- name: Install 'virtualenv' package
  pip:
    name: virtualenv
    executable: pip3

- name: Create virtualenv
  become: no
  pip:
    virtualenv: "{{ venv_dir }}"
    virtualenv_python: python3.8
    requirements: "{{ requirements_file }}"